#!/bin/bash

NOATT="true"
FILENAME=

while getopts "a:h" OPTION; do
  case $OPTION in
    a)
      NOATT="false"
  		echo "$4" | mutt -a "$OPTARG" -s "[POP] $3" -- $5
  		;;
    h)
      echo -e "\n\e[96m[+]\e[39m Utilisation de la commande \e[91msmail\e[39m:\n"
      echo -e "\e[96m[+]\e[39m \e[92m-h\e[39m: Affiche ce message"
      echo -e "\e[96m[+]\e[39m \e[92m-a \e[93m\"FICHIER\"\e[39m: Permet d'ajouter \e[93mFICHIER\e[39m en pièce jointe"
      exit 0
      ;;
    esac
done

if [[ $NOATT = "true" ]]
then
  echo "$2" | mutt -s "[POP] $1" -- $3
fi
