#!/bin/bash

if [[ "$(id -u)" != "0" ]]
then
	echo -e "\e[93mCe script doit être lancé en \e[91mROOT\e[39m"
fi

KRNLNAME=`uname -r`

echo -e "\e[96m[+]\e[39m Mise a jour du système"
apt-get update -y
apt-get upgrade -y
echo -e "\n\t\e[96m[+]\e[39m Mise a jour terminée..."

echo -e "\n\t\e[96m[+]\e[39m Installation des paquets manquant"
apt install -y linux-headers-amd64 linux-headers-$KRNLNAME gcc make perl
echo -e "\n\t\e[96m[+]\e[39m Installation terminée..."

/sbin/vboxconfig
